# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a77eed245a6595089fa6b191229db52e847ab95eba540a02ef7d6e415a0c8b95d66db49c0e23495e843ba49e7f503d678975932c2b6f0810c499444bf80f9f20

test:
  secret_key_base: 0e904a518b2d11aa731537d8874b3b448dd839c5c22bcfe9d10f953b0bf8f441c32394d260318eb99f493d9141588861b9601f9d867507c7f4788943acf92210

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
